drop table if exists bookmarks;

create table bookmarks ( 
    id INTEGER primary key generated by default as identity,
    title text,
    content text
);

insert into customers (title, content)
values
    ('Friends', 'Jeremy, Jerome, Jenson'),
    ('Things to do', 'Play basketball daily'),
    ('Plants', 'Sunflower, Grass')
    ('Best Electronics', 'Sony SRS-X55, iPhone 10, Samsung')
    ('Goals', 'Learn to sing, Learn to backflip on snowboard')
    ('Row 6', 'content on row 6')
    ('row 7', 'content 7')
    ('row 8', 'content 8')
    ('Row 9', 'content 9')
    ('row 10', 'content 10');